# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Download a file
      uses: carlosperate/download-file-action@v1.0.3
      id: download-poetry
      with:
        file-url: 'https://github.com/dita-ot/dita-ot/releases/download/2.5.4/dita-ot-2.5.4.zip'
        file-name: 'dita-ot-2.5.4.zip'
        location: './downloads'
       
    - name: Print the file path
      run: |
        echo "The file was downloaded to ${{ steps.download-poetry.outputs.file-path }}"
        unzip ./downloads/dita-ot-2.5.4.zip
        ls -lr .
      
    
    - name: checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        path: dita-in
        
    - name: checkout gh pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages 
        path: dita-out         
        
              
